-- Thanks to Amir Kibbar and Peter Rietzler for contributing the schema for H2 database,
-- and verifying that it works with Quartz's StdJDBCDelegate
--
-- Note, Quartz depends on row-level locking which means you must use the MVCC=TRUE
-- setting on your H2 database, or you will experience dead-locks
--
--
-- In your Quartz properties file, you'll need to set
-- org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate

CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR (200)  NOT NULL ,
  CALENDAR IMAGE NOT NULL
);

CREATE TABLE QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  CRON_EXPRESSION VARCHAR (120)  NOT NULL ,
  TIME_ZONE_ID VARCHAR (80)
);

CREATE TABLE QRTZ_FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  ENTRY_ID VARCHAR (95)  NOT NULL ,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  INSTANCE_NAME VARCHAR (200)  NOT NULL ,
  FIRED_TIME BIGINT NOT NULL ,
  SCHED_TIME BIGINT NOT NULL ,
  PRIORITY INTEGER NOT NULL ,
  STATE VARCHAR (16)  NOT NULL,
  JOB_NAME VARCHAR (200)  NULL ,
  JOB_GROUP VARCHAR (200)  NULL ,
  IS_NONCONCURRENT BOOLEAN  NULL ,
  REQUESTS_RECOVERY BOOLEAN  NULL
);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL
);

CREATE TABLE QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR (200)  NOT NULL ,
  LAST_CHECKIN_TIME BIGINT NOT NULL ,
  CHECKIN_INTERVAL BIGINT NOT NULL
);

CREATE TABLE QRTZ_LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  LOCK_NAME VARCHAR (40)  NOT NULL
);

CREATE TABLE QRTZ_JOB_DETAILS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  JOB_NAME VARCHAR (200)  NOT NULL ,
  JOB_GROUP VARCHAR (200)  NOT NULL ,
  DESCRIPTION VARCHAR (250) NULL ,
  JOB_CLASS_NAME VARCHAR (250)  NOT NULL ,
  IS_DURABLE BOOLEAN  NOT NULL ,
  IS_NONCONCURRENT BOOLEAN  NOT NULL ,
  IS_UPDATE_DATA BOOLEAN  NOT NULL ,
  REQUESTS_RECOVERY BOOLEAN  NOT NULL ,
  JOB_DATA IMAGE NULL
);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  REPEAT_COUNT BIGINT NOT NULL ,
  REPEAT_INTERVAL BIGINT NOT NULL ,
  TIMES_TRIGGERED BIGINT NOT NULL
);

CREATE TABLE qrtz_simprop_triggers
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INTEGER NULL,
    INT_PROP_2 INTEGER NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 BOOLEAN NULL,
    BOOL_PROP_2 BOOLEAN NULL,
);

CREATE TABLE QRTZ_BLOB_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  BLOB_DATA IMAGE NULL
);

CREATE TABLE QRTZ_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  JOB_NAME VARCHAR (200)  NOT NULL ,
  JOB_GROUP VARCHAR (200)  NOT NULL ,
  DESCRIPTION VARCHAR (250) NULL ,
  NEXT_FIRE_TIME BIGINT NULL ,
  PREV_FIRE_TIME BIGINT NULL ,
  PRIORITY INTEGER NULL ,
  TRIGGER_STATE VARCHAR (16)  NOT NULL ,
  TRIGGER_TYPE VARCHAR (8)  NOT NULL ,
  START_TIME BIGINT NOT NULL ,
  END_TIME BIGINT NULL ,
  CALENDAR_NAME VARCHAR (200)  NULL ,
  MISFIRE_INSTR SMALLINT NULL ,
  JOB_DATA IMAGE NULL
);

ALTER TABLE QRTZ_CALENDARS  ADD
  CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY
  (
    SCHED_NAME,
    CALENDAR_NAME
  );

ALTER TABLE QRTZ_CRON_TRIGGERS  ADD
  CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  );

ALTER TABLE QRTZ_FIRED_TRIGGERS  ADD
  CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY
  (
    SCHED_NAME,
    ENTRY_ID
  );

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS  ADD
  CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY
  (
    SCHED_NAME,
    TRIGGER_GROUP
  );

ALTER TABLE QRTZ_SCHEDULER_STATE  ADD
  CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY
  (
    SCHED_NAME,
    INSTANCE_NAME
  );

ALTER TABLE QRTZ_LOCKS  ADD
  CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY
  (
    SCHED_NAME,
    LOCK_NAME
  );

ALTER TABLE QRTZ_JOB_DETAILS  ADD
  CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY
  (
    SCHED_NAME,
    JOB_NAME,
    JOB_GROUP
  );

ALTER TABLE QRTZ_SIMPLE_TRIGGERS  ADD
  CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  );

ALTER TABLE QRTZ_SIMPROP_TRIGGERS  ADD
  CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  );

ALTER TABLE QRTZ_TRIGGERS  ADD
  CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  );

ALTER TABLE QRTZ_CRON_TRIGGERS ADD
  CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) REFERENCES QRTZ_TRIGGERS (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) ON DELETE CASCADE;


ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD
  CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) REFERENCES QRTZ_TRIGGERS (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) ON DELETE CASCADE;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD
  CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY
  (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) REFERENCES QRTZ_TRIGGERS (
    SCHED_NAME,
    TRIGGER_NAME,
    TRIGGER_GROUP
  ) ON DELETE CASCADE;


ALTER TABLE QRTZ_TRIGGERS ADD
  CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS FOREIGN KEY
  (
    SCHED_NAME,
    JOB_NAME,
    JOB_GROUP
  ) REFERENCES QRTZ_JOB_DETAILS (
    SCHED_NAME,
    JOB_NAME,
    JOB_GROUP
  );

-- Create tables to handle Advertisement and Schedulers associated

CREATE TABLE ADVERTISEMENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(256) NOT NULL,
	CATEGORY VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NAME VARCHAR(20),
	DESCRIPTION LONGTEXT,
	EMAIL_ENABLED VARCHAR(1),
	PHONE VARCHAR(20),
	PRICE VARCHAR(20),
    PUBLISHED INT DEFAULT 0,
    ALLOW_PUBLISH BOOLEAN DEFAULT TRUE
);

CREATE TABLE CATEGORY(
	ID VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IMAGE(
    PKEY INT PRIMARY KEY AUTO_INCREMENT,
	ID INT NOT NULL,
	LOCATION VARCHAR(512) NOT NULL
);

CREATE TABLE ADVERTISEMENT_JOB(
	ID INT NOT NULL,
	JOB_NAME VARCHAR(200) NOT NULL,
	JOB_GROUP VARCHAR(200) NOT NULL
);

ALTER TABLE ADVERTISEMENT_JOB ADD
  CONSTRAINT PK_ADVERTISEMENT_JOB PRIMARY KEY
  (
	ID,
	JOB_NAME,
	JOB_GROUP
  );

ALTER TABLE ADVERTISEMENT ADD
  CONSTRAINT FK_ADVERTISEMENT_CATEGORY FOREIGN KEY
  (
    CATEGORY
  ) REFERENCES CATEGORY (
    ID
  )ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE IMAGE ADD
  CONSTRAINT FK_IMAGE_ADVERTISEMENT FOREIGN KEY
  (
    ID
  ) REFERENCES ADVERTISEMENT (
    ID
  )ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ADVERTISEMENT_JOB ADD
  CONSTRAINT FK_ADVERTISEMENT_JOB_ADVERTISEMENT FOREIGN KEY
   (
	ID
   ) REFERENCES ADVERTISEMENT (
	ID
   ) ON DELETE CASCADE ON UPDATE CASCADE;



-- POPULATE CATEGORY TABLE

INSERT INTO CATEGORY VALUES('2', 'Computadoras>>PC de Escritorio');
INSERT INTO CATEGORY VALUES('3', 'Computadoras>>Laptop');
INSERT INTO CATEGORY VALUES('5', 'Computadoras>>Microprocesador');
INSERT INTO CATEGORY VALUES('4', 'Computadoras>>Monitor');
INSERT INTO CATEGORY VALUES('6', 'Computadoras>>Motherboard');
INSERT INTO CATEGORY VALUES('7', 'Computadoras>>Memoria RAM/FLASH');
INSERT INTO CATEGORY VALUES('8', 'Computadoras>>Disco Duro Interno/Externo');
INSERT INTO CATEGORY VALUES('9', 'Computadoras>>Chasis/Fuente');
INSERT INTO CATEGORY VALUES('11', 'Computadoras>>Tarjeta de Video');
INSERT INTO CATEGORY VALUES('12', 'Computadoras>>Tarjeta de Sonido/Bocinas');
INSERT INTO CATEGORY VALUES('13', 'Computadoras>>Quemador/Lector DVD/CD');
INSERT INTO CATEGORY VALUES('14', 'Computadoras>>Backup/UPS');
INSERT INTO CATEGORY VALUES('15', 'Computadoras>>Impresora/Cartuchos');
INSERT INTO CATEGORY VALUES('16', 'Computadoras>>Modem/Wifi/Red');
INSERT INTO CATEGORY VALUES('18', 'Computadoras>>Webcam/Microf/Audífono');
INSERT INTO CATEGORY VALUES('19', 'Computadoras>>Teclado/Mouse');
INSERT INTO CATEGORY VALUES('216', 'Computadoras>>Internet/Email');
INSERT INTO CATEGORY VALUES('218', 'Computadoras>>CD/DVD Virgen');
INSERT INTO CATEGORY VALUES('20', 'Computadoras>>Otros');
INSERT INTO CATEGORY VALUES('31', 'Compra / Venta>>Celulares/Líneas/Accesorios');
INSERT INTO CATEGORY VALUES('32', 'Compra / Venta>>Reproductor MP3/MP4/IPOD');
INSERT INTO CATEGORY VALUES('33', 'Compra / Venta>>Reproductor DVD/VCD/DVR');
INSERT INTO CATEGORY VALUES('214', 'Compra / Venta>>Televisor');
INSERT INTO CATEGORY VALUES('34', 'Compra / Venta>>Cámara Foto/Video');
INSERT INTO CATEGORY VALUES('213', 'Compra / Venta>>Aire Acondicionado');
INSERT INTO CATEGORY VALUES('39', 'Compra / Venta>>Consola Videojuego/Juegos');
INSERT INTO CATEGORY VALUES('43', 'Compra / Venta>>Satélite');
INSERT INTO CATEGORY VALUES('35', 'Compra / Venta>>Electrodomésticos');
INSERT INTO CATEGORY VALUES('36', 'Compra / Venta>>Muebles/Decoración');
INSERT INTO CATEGORY VALUES('37', 'Compra / Venta>>Ropa/Zapato/Accesorios');
INSERT INTO CATEGORY VALUES('40', 'Compra / Venta>>Intercambio/Regalo');
INSERT INTO CATEGORY VALUES('41', 'Compra / Venta>>Mascotas/Animales');
INSERT INTO CATEGORY VALUES('42', 'Compra / Venta>>Divisas');
INSERT INTO CATEGORY VALUES('38', 'Compra / Venta>>Libros/Revistas');
INSERT INTO CATEGORY VALUES('211', 'Compra / Venta>>Joyas/Relojes');
INSERT INTO CATEGORY VALUES('217', 'Compra / Venta>>Antiguedades/Colección');
INSERT INTO CATEGORY VALUES('219', 'Compra / Venta>>Implementos Deportivos');
INSERT INTO CATEGORY VALUES('44', 'Compra / Venta>>Otros');
INSERT INTO CATEGORY VALUES('83', 'Servicios>>Clases/Cursos');
INSERT INTO CATEGORY VALUES('71', 'Servicios>>Informática/Programación');
INSERT INTO CATEGORY VALUES('72', 'Servicios>>Películas/Series/Videos');
INSERT INTO CATEGORY VALUES('73', 'Servicios>>Limpieza/Doméstico');
INSERT INTO CATEGORY VALUES('74', 'Servicios>>Foto/Video');
INSERT INTO CATEGORY VALUES('75', 'Servicios>>Construcción/Mantenimiento');
INSERT INTO CATEGORY VALUES('76', 'Servicios>>Reparación Electrónica');
INSERT INTO CATEGORY VALUES('77', 'Servicios>>Peluquería/Barbería/Belleza');
INSERT INTO CATEGORY VALUES('78', 'Servicios>>Restaurantes/Gastronomía');
INSERT INTO CATEGORY VALUES('79', 'Servicios>>Diseño/Decoración');
INSERT INTO CATEGORY VALUES('80', 'Servicios>>Música/Animación/Shows');
INSERT INTO CATEGORY VALUES('81', 'Servicios>>Relojero/Joyero');
INSERT INTO CATEGORY VALUES('220', 'Servicios>>Gimnasio/Masaje/Entrenador');
INSERT INTO CATEGORY VALUES('82', 'Servicios>>Otros');
INSERT INTO CATEGORY VALUES('101', 'Vivienda>>Compra/Venta');
INSERT INTO CATEGORY VALUES('102', 'Vivienda>>Permuta');
INSERT INTO CATEGORY VALUES('103', 'Vivienda>>Alquiler a cubanos');
INSERT INTO CATEGORY VALUES('104', 'Vivienda>>Alquiler a extranjeros');
INSERT INTO CATEGORY VALUES('105', 'Vivienda>>Casa en la playa');
INSERT INTO CATEGORY VALUES('121', 'Autos>>Carros');
INSERT INTO CATEGORY VALUES('122', 'Autos>>Motos');
INSERT INTO CATEGORY VALUES('215', 'Autos>>Bicicletas');
INSERT INTO CATEGORY VALUES('125', 'Autos>>Piezas/Accesorios');
INSERT INTO CATEGORY VALUES('124', 'Autos>>Alquiler');
INSERT INTO CATEGORY VALUES('123', 'Autos>>Mecánico');
INSERT INTO CATEGORY VALUES('204', 'Autos>>Otros');
INSERT INTO CATEGORY VALUES('161', 'Empleos>>Ofertas de empleo');
INSERT INTO CATEGORY VALUES('162', 'Empleos>>Busco empleo');

COMMIT;
